global:
  scrape_interval: 15s  # Default scrape interval for all jobs.

scrape_configs:
  - job_name: 'spring-app'           # A name for this job.
    metrics_path: '/actuator/prometheus' # The endpoint for Spring Boot metrics.
    scrape_interval: 5s              # How often to scrape this target.
    static_configs:
      - targets: ['app:8080']        # Replace 'app' with the container name of your app service.
